### ISSUE TITLE
NetCore [Q&A] 

### ISSUE THREAD

**Issue by JuandreG** [ArasLabs/innovator-client-example#3]
Does the IOM.dll only work on NetFramework or can I use it with NetCore? 

I ask because when I try to use it in a UWP application I get some reference issues.

**Comment by cgillis-aras** [comment]
The IOM is built against the .NET framework, so it is not available for use in a .NET Core application. For most of the external applications I build now, I perform my queries using the [Aras REST API](https://community.aras.com/b/english/posts/tech-tip-using-the-aras-restful-api) to avoid needing to reference the IOM at all. Authentication will work a little differently, so I'd recommend checking out our blog post on using [token authentication](https://community.aras.com/b/english/posts/token-authentication-using-the-rest-api).
